### ISSUE TITLE
Documentation update, running via vagrant or boot2docker

### ISSUE THREAD

**Issue by rmarscher** [davenuman/bowline#31]
Thanks again for sharing this project.

If you are using bowline on a system that doesn't support docker natively (i.e. OS X), it's easier to bind the apache and mysql using `ports` instead of `expose` in the docker-compose.yml. Otherwise, it seemed to be necessary to modify the iptables to route the container ip through the VM running docker (which is typically boot2docker or vagrant). Without that, it didn't seem possible to open Drupal in a browser.

I saw some lingering notes about using `route` to setup that routing. In my case, my VM had an IP address of 172.17.8.101. Docker was assigning IPs to containers at 10.1.0.xx. So running this command in OS X terminal added the routing I needed: `sudo route -n add 10.1.0.0/24 172.17.8.101`. I was then able to access Drupal at the 10.1.0.2 address I saw after running `bowline`.

Also, the invoke_proxy command doesn't work out of the box, because *.localtest.me (i.e. 127.0.0.1) doesn't point to the VM IP. If vagrant's port forwarding config is used to bind port 80 in the vagrant box to port 80 in the host machine, then it would work. Another option is to use nginx on the host machine to reverse proxy .localtest.me to the vagrant box. Here's an nginx server block that worked for me to do that.

```
server {
    listen   80;
    server_name .localtest.me;
    location / {
        proxy_pass http://172.17.8.101:80;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host            $host;
        proxy_set_header        X-Forwarded-Proto $scheme;
        add_header              Front-End-Https   on;
        proxy_redirect     off;
    }
}
```

The alternative that I found to be better for my workflow is changing the docker-compose-yml to this:

```
db:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpass
    - MYSQL_DATABASE=drupal
    - MYSQL_HOME=/etc
  volumes:
    - .docker/etc/my.cnf:/etc/my.cnf
  hostname: dbhost
  expose:
    - "3306"
  dns:
    - 8.8.8.8
    - 8.8.4.4
web:
  image: davenuman/bowline-web-php:latest
  command: /start.sh
  environment:
    - COMPOSER_HOME=/.composer
  ports:
    - "80:80"
  expose:
    - "80"
    - "9000"
  volumes:
    - .:/var/www
  links:
    - db:dbhost
  hostname: drupal
  dns:
    - 8.8.8.8
    - 8.8.4.4
```

The only change is inserting the `ports` section to map port 80 in the web container. Then it's easy to access Drupal via the VM IP.

Thanks again. I don't think there is one way to do this that will match everyone's way of running a docker development environment. I thought it might be helpful to note this option in case others struggle with the network routing.
